### ISSUE TITLE
Separate the Actions of Placing a Tower and Selecting a Tower

### ISSUE THREAD

**Issue by stoplime** [stoplime/inkTD#12]
Currently it always set to place a tower unless the mouse clicks on a tower. We want it to have it place towers only when the tower buy menu is up. Then we also want to be able to select a tower when the tower menu is closed or upgrade menu is up.

**Comment by tadams0** [comment]
This has been added and/or fixed as of this [commit](https://github.com/stoplime/inkTD/commit/218ac99cfc633121041eb430b9555d55cd63d025).
