### ISSUE TITLE
Selected Tower Menu has a bad Lighting on the tower icon

### ISSUE THREAD

**Issue by stoplime** [stoplime/inkTD#2]
The icon is bad with random colors overlaying the tower image

**Comment by stoplime** [comment]
Potential Fix: delay tower snapshots by like a second for the lighting to setup.

**Comment by tadams0** [comment]
This has been resolved as of this [commit](https://github.com/stoplime/inkTD/commit/218ac99cfc633121041eb430b9555d55cd63d025).
